language: node_js
node_js:
  - "7.2.0"
install:
  - npm install

script:
  - npm run build
  - npm test
  - npm run coverage
  - ./node_modules/coveralls/bin/codecov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js